// import { Index } from './index';
import Head from "next/head";
import React from "react";
import Land from "../../../contact-us/land-careers";
import About from "../../../contact-us/about";
import Services from "../../../contact-us/services";
import Founded from "../../../contact-us/founded";
import Vision from "../../../contact-us/vision";
// import Services from "./services";

export default function index() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Land />

      <About />
      <Services />

      <Founded />
      <Vision />
      {/* <article id="OurTeam">
        <p>
          We have a full complement of professionals with the right credentials
          to fully support and serve our clients.
        </p>

        <aside id="team-area">
          <div>
            image goes here
            <div>
              <h3>C.E.O / Founder</h3>
              <h4>MR LOT MUCAVELE</h4>
            </div>
          </div>
        </aside>
      </article> */}
    </>
  );
}
