// import { Index } from './index';
import Head from "next/head";
import React from "react";
import Land from "../../services/_land";
import Pictures from "../../services/_pictures";
import axios from "axios";
import { useRouter } from "next/router";
import { GraphQLClient, gql } from "graphql-request";

export default function Index({ data }: any) {
  const router = useRouter();
  const { slug } = router.query;

  // console.log(slug)

  // console.log(data)
  // const name = data.sorted;
  const shoot = data.theName;
  const shootAll = data.theNameAll;

  // console.log(shootAll);

  return (
    <>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      services go here
      <Land data={shoot} />
      {/* <article id="article">
        WE PPROMISE RESPECT
        <h2> Mechanical and Civil Constuction</h2>
        <ul>
          <li>Steel fabrication and construction</li>
          <li>Mechanical construction and pipes installation</li>
          <li>
            Erection of steel structure - We do Steel welding, Stainless,
            Aluminum, Copper and plastic
          </li>
          <li>
            We weld Structures, pipelines, tanks, pressure vessels and boilers
          </li>
        </ul>
      </article> */}
      <Pictures data={shoot} dataAll={shootAll} />
      <aside>
        Our Other Services
        <ul>
          <li>Mechanical and Civil Constrution</li>
          <li>Water Treatment</li>
          <li>
            Supply, Services, Repair and Installation of Workshop Machines
          </li>
          <li>Road Construction</li>
          <li>HVAC Services</li>
          <li>Workshop Equipment Supply</li>
          <li>Agricultural Engineering</li>
          <li>Electrical Engineering</li>
          <li>Renewable Energy</li>
          <li>PAC Housing</li>
          <li>Barricades</li>
          {/* <li></li> */}
        </ul>
      </aside>
    </>
  );
}

export async function getServerSideProps(context: any) {
  // console.log(serviceResponse.data);
  const { params } = context;
  const slugId = params.slug;

  // const x = await axios.post("http://127.0.0.1:3000/api/postTest", {
  //   slug: slugId,
  // });

  const graphQLClient = new GraphQLClient("http://127.0.0.1:1337/graphql");

  const variables = {
    slug: slugId,
  };

  const query = gql`
    query ($slug: String!) {
      services(filters: { slug: { eq: $slug } }) {
        data {
          attributes {
            Name

            Task {
              Task
            }

            Images {
              __typename
              ... on UploadFileRelationResponseCollection {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  `;

  const queryAll = gql`
    query {
      services {
        data {
          attributes {
            Name
            slug
            Images {
              __typename
              ... on UploadFileRelationResponseCollection {
                data {
                  attributes {
                    url
                  }
                }
              }
            }

            Task {
              Task
            }
          }
        }
      }
    }
  `;

  const data = await graphQLClient.request(query, variables);

  const attributes = data.services.data;

  const dataAll = await graphQLClient.request(queryAll);

  const attributesAll = dataAll.services.data;

  const datad = {
    theName: attributes,
    theNameAll: attributesAll,
  };

  // const serviceResponse = await axios.get("http://localhost:3000/api/postTest");

  // console.log(serviceResponse)
  return {
    props: {
      data: datad,
    },
  };
}
